### ISSUE TITLE
Refactor GPU node spec in radixconfig

### ISSUE THREAD

**Issue by nilsgstrabo** [equinor/radix-operator#1004]
We should simplify the node spec (https://www.radix.equinor.com/references/reference-radix-config/#node) in radixconfig.yaml.
Today the user sets gpu and gpuCount. radix-operator translates this into a toleration and a nodeAffinity selector.
The current node spec does not support definition VM types, e.g. with more/faster memory and cpus. It is bound to GPU types only.

I suggest we deprecate/delete the current node spec and replace with a "simple" string value, e.g. nodeType: nv-v100-2, where nv-v100-2 is in a fixed list of nodes types (mapped to a Azure VM size). We can then add new nodepools with new vm types and add the new vm type to the list of supported types.

Use labels to direct the pod to correct nodepool.

## ~~Option 1~~
~~Map in helm chart of nodetype (name => {arch, features, description})~~
- make map available as configMap
- Mount map into operator + all pipeline runners
- RX validate needs the data?

## Option 2
Map in yaml, generate go code
ref. https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_instance_types/gen.go#L35

# map of nodeTypes

Create new runtime package, and move existing utils/runtime in here

create `map[string]NodeType`
```yaml
nodeTypes = : 
- memory-optimized-v1:  #[Standard_M96s_2_v3](https://cloudprice.net/vm/Standard_M96s_2_v3) # 2000gb
     arch: x86

# to be decied:
- memory-optimized-2-v1:  #[Standard_M146s_2_v3](https://cloudprice.net/vm/Standard_M96s_2_v3) # 4000gb
     arch: x86
     
- gpu-a100-v1:
     arch: x86
     deprecated:
       mesg: whatv
       replacedBy: gpu-a100-8-v1 

- gpu-a100-2:
     arch: x86

- gpu-a100-4:
     arch: x86
```

# radixconfig.yaml structure
```
- component|job:
  resources:
    limits:
      cpu: 16
      mem: 250Gi

  runtime:
    # arch: x86
    nodeType: radix-highcpu-v1 | radix-highmem-v1 | radix-gpu-intel-v1 | radix-gpu-nvidia-v1 
```

# Radix Platform:
Create node pools with:
```
taints: radix-nodetype=radix-highmem-v1
labels: radix-nodetype=radix-highmem-v1
```

DoD:
In radixconfig it must be possible to add extra information to select different node types

Runtime property have architecture and nodeType.

- Validation: specifying both nodeType and architecture must fail
- If arch is specified: build and run on target architecture
- if nodeType: validate name against map of available nodeTypes
- if nodeType: build on the matching nodeType from node type map
- if nodeType: run on node matching specified nodeType
- map of nodeTypes, see **#map of nodeTypes** above
- if nodeType: add tolerations as well as the existing node selectors (requiredDuringScheduling..., labels)
