### ISSUE TITLE
Update radixconfig.yaml to support selecting different type node-pools, ARM- and AMD nodepool

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-operator#1123]
Add new configuration section in radixconfig

```
spec:
  components:
    - name: frontend
      runtime:
        arch: amd64 
      environmentConfig:
        - environment: qa
          runtime: 
            arch: amd64 
  jobs:
    - name: compute
      runtime:
        arch: amd64
      environmentConfig:
        - environment: qa
          runtime: 
            arch: amd64          
```
