### ISSUE TITLE
Spike: Distro for radix-operator

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-operator#1267]
Create a workflow for distribution of radix-operator

DoD
Implement sample
Provide a workflow drawing (simple)

**Comment by Richard87** [comment]
# Goals:

1. Good dev-experience
2. Easy to know versions being installed
3. Easy to manage across clusters
4. All versions should be SemVer with `v` prefix

# Radix Helm Distribution

Main Chart starting point (example):
```
apiVersion: v2
name: app-distro
version: v1.0.0
dependencies:
  - name: radix-operator
    version: v1.0.0
  - name: radix-api
    version: v1.0.0
  - name: radix-web-console
    version: v1.0.0
  - name: radix-github-webhook
    version: v1.0.0
```

## After Radix-API is updated with new tag v1.1.0
(Question, should we always update a patch/minor version when promoting from dev to QA, or should we use master/latest-timestamp?)


```
apiVersion: v2
name: app-distro
version: v1.0.0-rc1
dependencies:
  - name: radix-operator
    version: v1.0.0
  - name: radix-api
    version: v1.1.0
  - name: radix-web-console
    version: v1.0.0
  - name: radix-github-webhook
    version: v1.0.0
```

## When QA is confirmed to be stable, relase a new version of Distro:

```
apiVersion: v2
name: app-distro
version: v1.1.0
dependencies:
  - name: radix-operator
    version: v1.0.0
  - name: radix-api
    version: v1.1.0
  - name: radix-web-console
    version: v1.0.0
  - name: radix-github-webhook
    version: v1.0.0
```
