### ISSUE TITLE
VolumeMount `azure-blob` type  re-deploy fails validation

### ISSUE THREAD

**Issue by satr** [equinor/radix-operator#1287]
With configuration, using `azure-blob`, re-deploy fails validation

```
  components:
    - name: server
      volumeMounts:
        - name: storage
          path: /app/image-storage
          type: azure-blob
          storage: testdata
          uid: 1000
``` 
Error

```
Failed to run error="failed volumeMount validation for component server. volumeMount storage2 failed validation. blobFuse2 failed validation. container not set"
```
