### ISSUE TITLE
Improve the release process for the radix-operator.

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-operator#846]
Using helm-charts without a proper version connection is troublesome.

Look into new ways of releasing this component.

**Comment by Richard87** [comment]
I have tested the following which I think might be a good solution for us:

Prod Service `version: ">=1.0.0 < 2.0.0"`
Dev service `version: ">= 1.0.0-0 < 2.0.0-0"`

Prod release is tagged with `1.X.X` 
Dev release is tagged with `1.X.X-nightly.TIMESTAMP`

Interesting discussion: https://github.com/fluxcd/flux2/issues/1298


Helm Github steps:
```yaml
- name: Update helm chart
  id: update
  working-directory: infrastructure
  run: |
    yq -i '.version = "${{ steps.read.outputs.version }}"' Chart.yaml
    yq -i '.appVersion = "${{ steps.read.outputs.version }}"' Chart.yaml

- name: Helm Login
  run: |
    helm registry login happydogsprod.azurecr.io \
      --username helmuser \
      --password ${{secrets.HELM_REPO_SECRET}}

- name: package & push
  working-directory: infrastructure
  run: |
    helm package .
    helm push appname-${{ steps.read.outputs.version }}.tgz oci://repository.azurecr.io/helm
```
